import type { Project } from './project.model'

export const projects: Project[] = [
    {
        title: 'Sheresta',
        category: 'Legal Platform',
        thumbnail: 'portfolio/sheresta.png',
        images: [
            'portfolio/sheresta.png',
            'portfolio/Sheresta/case-list.png',
            'portfolio/Sheresta/cause-list.png',
            'portfolio/Sheresta/document.png',
            'portfolio/Sheresta/case-event.png',
            'portfolio/Sheresta/organization.png',
        ],
        summary: 'Smart Legal Case Management Platform',
        description:
            'A modern legal case management platform that helps law firms organize case documents, track real-time updates, manage court schedules, and access daily cause lists. It also includes a client portal where clients can securely follow case progress and stay updated on hearings, tasks, and important developments.',
        client: 'Sheresta',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'TypeScript', 'PostgreSQL', 'HonoJS', 'Drizzle'],
        link: 'https://sheresta.com',
    },
    {
        title: 'Quizzaro',
        category: 'Entertainment',
        thumbnail: 'portfolio/quizzaro.png',
        images: [
            'portfolio/quizzaro.png',
            'portfolio/Quizzaro/quiz.png',
            'portfolio/Quizzaro/game-list.png',
            'portfolio/Quizzaro/rank.png',
            'portfolio/Quizzaro/rank-list.png',
            'portfolio/Quizzaro/knowladge.png',
        ],
        summary: 'Play, Learn & Win Quiz Platform',
        description:
            'An interactive quiz platform where users can test their knowledge, compete with others, and win real cash prizes. Designed for both desktop and mobile, Quizzaro combines education, entertainment, and fast-paced gameplay to create an exciting and rewarding quiz experience.',
        client: 'Quizzaro',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Node.js', 'Socket.io'],
        link: 'https://quizzaro.com',
    },
    {
        title: 'Lieblings Mode',
        category: 'Ecommerce',
        thumbnail: 'portfolio/libslingsmode.png',
        images: [
            'portfolio/libslingsmode.png',
            'portfolio/Lieblings-Mode/product-category.png',
            'portfolio/Lieblings-Mode/product-design.png',
            'portfolio/Lieblings-Mode/product-design-custom-image.png',
            'portfolio/Lieblings-Mode/single-product.png',
            'portfolio/Lieblings-Mode/terndig-product.png',
        ],
        summary: 'Custom Fashion Design & E-Commerce Platform',
        description:
            'An online fashion platform offering stylish and affordable clothing for men, women, and children. It features an interactive design canvas that allows customers to customize and create their own T-shirts and dresses by adding designs, text, and graphics before ordering.',
        client: 'Lieblings Mode',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Stripe', 'Tailwind CSS', 'Prisma'],
        link: 'https://lieblings-mode.com',
    },
    {
        title: 'ContentERP',
        category: 'Enterprise',
        thumbnail: 'portfolio/contenterp.png',
        images: [
            'portfolio/contenterp.png',
            'portfolio/ContentERP/Dashboard.png',
            'portfolio/ContentERP/Dashboard-Article-Editor.png',
            'portfolio/ContentERP/Dashboard-Contents.png',
            'portfolio/ContentERP/Dashboard-Queue.png',
            'portfolio/ContentERP/Dashboard-Chat.png',
            'portfolio/ContentERP/Dashboard-Social.png',
        ],
        summary: 'Smart Content Workflow Platform',
        description:
            'An all-in-one content management and workflow platform designed to streamline the entire content creation process—from idea generation to publishing—while enabling team collaboration, task automation, analytics, and seamless integrations in a single centralized system.',
        client: 'ContentERP',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Node.js', 'PostgreSQL', 'Prisma'],
        link: 'https://contenterp.com',
    },
    {
        title: 'Shared Auth',
        category: 'Enterprise',
        thumbnail: 'portfolio/shared_auth.png',
        images: ['portfolio/shared_auth.png'],
        summary: 'Enterprise Identity Management System',
        description:
            'A centralized authorization engine built to manage hierarchical organizational structures. It facilitates secure user onboarding, organization-specific group creation, and granular Role-Based Access Control (RBAC). The system enables administrators to define custom permissions and manage user access levels within specific organization and group boundaries.',
        client: 'Shared Auth',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Hono.js', 'PostgreSQL', 'Drizzle'],
    },
    {
        title: 'PdfAir',
        category: 'Tools',
        thumbnail: 'portfolio/pdfair.png',
        images: ['portfolio/pdfair.png'],
        summary: 'Manage and Sync Your PDF Library Across Devices',
        description:
            'You have always wanted to read the books in your collection. You see interesting artictes online and want to save it as PDF to read it later. But you dont have enough time. Also, you forget where you stored them.',
        client: 'PdfAir',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'HONOJS', 'DRIZZLE', 'POSTGRESQL'],
        link: 'https://pdfair.com/',
    },
]
