import type { Project } from './project.model'

export const projects: Project[] = [
    {
        title: 'Sheresta',
        category: 'Legal Platform',
        thumbnail: 'projects/Sheresta/main.png',
        images: [
            'projects/Sheresta/main.png',
            'projects/Sheresta/case-list.png',
            'projects/Sheresta/cause-list.png',
            'projects/Sheresta/document.png',
            'projects/Sheresta/case-event.png',
            'projects/Sheresta/organization.png',
        ],
        summary: 'Smart Legal Case Management Platform',
        description:
            'A modern legal case management platform that helps law firms organize case documents, track real-time updates, manage court schedules, and access daily cause lists. It also includes a client portal where clients can securely follow case progress and stay updated on hearings, tasks, and important developments.',
        client: 'Sheresta',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'TypeScript', 'PostgreSQL', 'HonoJS', 'Drizzle'],
        link: 'https://sheresta.com',
    },
    {
        title: 'Quizzaro',
        category: 'Entertainment',
        thumbnail: 'projects/Quizzaro/main.png',
        images: [
            'projects/Quizzaro/main.png',
            'projects/Quizzaro/quiz.png',
            'projects/Quizzaro/game-list.png',
            'projects/Quizzaro/rank.png',
            'projects/Quizzaro/rank-list.png',
            'projects/Quizzaro/knowladge.png',
        ],
        summary: 'Play, Learn & Win Quiz Platform',
        description:
            'An interactive quiz platform where users can test their knowledge, compete with others, and win real cash prizes. Designed for both desktop and mobile, Quizzaro combines education, entertainment, and fast-paced gameplay to create an exciting and rewarding quiz experience.',
        client: 'Quizzaro',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Node.js', 'Socket.io'],
        link: 'https://quizzaro.com',
    },
    {
        title: 'Lieblings Mode',
        category: 'Ecommerce',
        thumbnail: 'projects/Lieblings-Mode/main.png',
        images: [
            'projects/Lieblings-Mode/main.png',
            'projects/Lieblings-Mode/product-category.png',
            'projects/Lieblings-Mode/product-design.png',
            'projects/Lieblings-Mode/product-design-custom-image.png',
            'projects/Lieblings-Mode/single-product.png',
            'projects/Lieblings-Mode/terndig-product.png',
        ],
        summary: 'Custom Fashion Design & E-Commerce Platform',
        description:
            'An online fashion platform offering stylish and affordable clothing for men, women, and children. It features an interactive design canvas that allows customers to customize and create their own T-shirts and dresses by adding designs, text, and graphics before ordering.',
        client: 'Lieblings Mode',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Stripe', 'Tailwind CSS', 'Prisma'],
        link: 'https://lieblings-mode.com',
    },
    {
        title: 'ContentERP',
        category: 'Enterprise',
        thumbnail: 'projects/ContentERP/main.png',
        images: [
            'projects/ContentERP/main.png',
            'projects/ContentERP/Dashboard.png',
            'projects/ContentERP/Dashboard-Article-Editor.png',
            'projects/ContentERP/Dashboard-Contents.png',
            'projects/ContentERP/Dashboard-Queue.png',
            'projects/ContentERP/Dashboard-Chat.png',
            'projects/ContentERP/Dashboard-Social.png',
        ],
        summary: 'Smart Content Workflow Platform',
        description:
            'An all-in-one content management and workflow platform designed to streamline the entire content creation process—from idea generation to publishing—while enabling team collaboration, task automation, analytics, and seamless integrations in a single centralized system.',
        client: 'ContentERP',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Node.js', 'PostgreSQL', 'Prisma'],
        link: 'https://contenterp.com',
    },
    {
        title: 'Shared Auth',
        category: 'Enterprise',
        thumbnail: 'projects/Shared-Auth/main.png',
        images: ['projects/Shared-Auth/main.png'],
        summary: 'Enterprise Identity Management System',
        description:
            'A centralized authorization engine built to manage hierarchical organizational structures. It facilitates secure user onboarding, organization-specific group creation, and granular Role-Based Access Control (RBAC). The system enables administrators to define custom permissions and manage user access levels within specific organization and group boundaries.',
        client: 'Shared Auth',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Hono.js', 'PostgreSQL', 'Drizzle'],
    },
    {
        title: 'PdfAir',
        category: 'Tools',
        thumbnail: 'projects/PdfAir/main.png',
        images: ['projects/PdfAir/main.png'],
        summary: 'Manage and Sync Your PDF Library Across Devices',
        description:
            'You have always wanted to read the books in your collection. You see interesting artictes online and want to save it as PDF to read it later. But you dont have enough time. Also, you forget where you stored them.',
        client: 'PdfAir',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'HONOJS', 'DRIZZLE', 'POSTGRESQL'],
        link: 'https://pdfair.com/',
    },
    {
        title: 'Michrobux',
        category: 'Ecommerce',
        thumbnail: 'projects/Michrobux/main.png',
        images: [
            'projects/Michrobux/main.png',
            'projects/Michrobux/hot-products.png',
            'projects/Michrobux/product-details.png',
            'projects/Michrobux/player-says.png',
        ],
        summary: 'Level Up Your Roblox Experience',
        description:
            'A dedicated e-commerce platform for Roblox players to purchase Robux, game cards, and exclusive in-game items for popular titles like Pet Sim X and Blox Fruits. Features include secure transactions, flash sales, instant delivery, and a seamless user experience.',
        client: 'Michrobux',
        year: '2024',
        role: 'Full product build',
        stack: ['Angular', 'Node.js', 'Tailwind CSS'],
    },
    {
        title: 'Montuams',
        category: 'Automotive',
        thumbnail: 'projects/Montuams/main.png',
        images: [
            'projects/Montuams/main.png',
            'projects/Montuams/service-deal.png',
            'projects/Montuams/appoinments-review.png',
        ],
        summary: 'Professional Auto Repair and Maintenance Services',
        description:
            "A professional landing page for Montuam's Auto Services, designed to attract local customers and streamline appointment bookings. The site features a clear breakdown of automotive services, promotional offers, customer testimonials, an interactive FAQ section, and a direct Google Maps integration for easy location access.",
        client: 'Montuams',
        year: '2024',
        role: 'Full project build',
        stack: ['Angular', 'Tailwind CSS', 'Node.js', 'Drizzle', 'PostgreSQL'],
    },
    {
        title: 'Al-Firdaous',
        category: 'Community',
        thumbnail: 'projects/Mosque/main.png',
        images: [
            'projects/Mosque/main.png',
            'projects/Mosque/seeking-clarity-in-islam.png',
            'projects/Mosque/upcomming-events.png',
        ],
        summary: 'Comprehensive Mosque Management & Community Platform',
        description:
            "A comprehensive platform designed for mosques to manage their daily operations and connect with the community. It features real-time prayer schedules, event management, announcements, spiritual guidance resources, and a direct 'Ask Shaykh' Q&A system to foster community engagement and learning.",
        client: 'Al-Firdaous',
        year: '2024',
        role: 'Full project build',
        stack: ['Angular', 'Tailwind CSS', 'Node.js', 'Drizzle', 'PostgreSQL'],
    },
]
